application: xuu-a000
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /api/.*
  script: main.php

- url: /lib
  static_dir: lib

- url: /(^\.)?
  static_files: index.html
  upload: index.html

- url: /(.*?)/
  static_files: index.html
  upload: index.html
  
- url: /
  static_dir: app
